const data = {
  id: 'شناسه',
  name: 'نام',
  organizationId: 'شناسه سازمانی',
  inputType: 'نوع فیلد ورودی',
  type: 'نوع',
  columnCategory: 'دسته ستون',
  dataType: 'نوع داده',
  informationClass: 'کلاس داده',
  status: 'وضعیت',
  documentType: 'نوع سند',
  title: 'عنوان',
  targetLevantId: 'شناسه لوانت موردنظر',
  applicationName: 'نام اپلیکیشن',
  levantId: 'شماره لوانت',
  action: 'نوع فعالیت',
  text: 'متن',
  actorType: 'نوع عمل',
  crudType: 'نوع عملیات',
  callType: 'نوع تماس',
  subject: 'موضوع',
  code: 'کد',
  description: 'توضیحات',
  phoneNumber: 'شماره تلفن',
  voipCallId: 'کد تماس',
  organizationNumber: 'شماره سازمانی',
  extensionNumber: 'داخلی',
  callerFullName: 'نام تماس گیرنده',
  editBy: 'ویرایش شده توسط',
  editDate: 'تاریخ ویرایش',
  prevSubject: 'موضوع تماس قبلی',
  currentSubject: 'موضوع تماس جدید',
  prevDescription: 'توضیحات تماس قبلی',
  currentDescription: 'توضیحات تماس جدید',
  prevFollowUp: 'نیاز به پیگیری قبلی',
  currentFollowUp: 'نیاز به پیگیر فعلی',
  prevFollowMessage: 'پیام نیاز به پیگیری قبلی',
  currentFollowMessage: 'پیام نیاز به پیگیری جدید',
  prevType: 'نوع تماس قبلی',
  currentType: 'نوع تماس جدید',
  caseId: 'کد درخواست',
  caseChannel: 'کانال ورودی',
  caseOwnerFullName: 'درخواست دهنده',
  caseOwnerLevantId: 'لوانت درخواست دهنده',
  reporterFullName: 'ایجاد شده توسط',
  reporterLevantId: 'لوانت ایجاد کننده',
  ownerFullName: 'درخواست دهنده',
  ownerLevantId: 'لوانت درخواست دهنده',
  editedByFullName: 'ویرایش شده توسط',
  editedByLevantId: 'لوانت ویرایش شده',
  prevPriority: 'اولویت قبلی',
  currentPriority: 'اولویت جدید',
  prevCaseAssignLevantId: 'کاربر قبلی',
  currentCaseAssignLevantId: 'کاربر جدید',
  caseAnswerType: 'نوع پاسخ درخواست',
  answeredByFullName: 'پاسخ داده شده توسط',
  answeredByLevantId: 'لوانت پاسخ دهنده',
  answerDate: 'تاریخ ثبت پاسخ',
};
const dataTranslatorExport = key => (data[key] ? data[key] : false);

export default dataTranslatorExport;
