export const Actions = {
  viewCallDetail: 'VOIP_CALL_CALL_DETAILS_CREATE',
  updateCallDetail: 'VOIP_CALL_UPDATE',
  callsAllTab: 'VOIP_CALL_ALL',

  downloadPhoneCallExcelBusiness: 'ROLE_BUSINESS_LEAD_EXPORT_DYNAMIC_READ',
  paratyExcelReportReadPerson: 'ROLE_PARTY_EXCEL_REPORT_READ',
  paratyExcelReportReadBusiness: 'ROLE_BUSINESS_PARTY_EXCEL_REPORT_READ',

  createCase: 'CASE_CREATE',
  showCase: 'CASE_SHOW',
  updateCase: 'CASE_UPDATE',

  createTask: 'TASK_MANAGEMENT_UPDATE',
  deleteTask: 'TASK_MANAGEMENT_DELETE',
  showTask: 'TASK_MANAGEMENT_READ',
  updateTaskStatus: 'TASK_MANAGEMENT_CHANGE_STATUS_UPDATE',

  addKycTimeManagement: 'HUMAN_RESOURCE_CREATE',
  downloadKycTimeManagementExcel: 'HUMAN_RESOURCE_EXPORT_EXCEL_READ',

  editInLeadProfile: 'PARTY_ADDITIONAL_INFO_CREATE',
  printForm: 'FORM_PDF_READ',
  businessStackHoldersAndRolesTab: 'PROFILE_RELATIONS_READ',
  documentAll: 'DOCUMENT_ALL',
  persoanlOpprotunitesListTab: 'OPPORTUNITY_GET_BY_LEVANT_ID_READ',
  caseAllReadTab: 'CASE_ALL_READ',
  sessionAllRead: 'SESSION_ALL_READ',
  salesOpportunitiesTab: 'SALE_OPPORTUNITY_ALL_READ',

  activityAllRead: 'ACTIVITY_ALL_READ',
  activityTimelineRead: 'ACTIVITY_TIMELINE_READ',
  viewActivity: 'ACTIVITY_READ',

  sendSms: 'CONTACT_CENTER_SEND_SMS_CREATE',
  sendEmail: 'CONTACT_CENTER_SEND_EMAIL_CREATE',

  leadAssign: 'LEAD_ASSIGN_CREATE',
  leadUnAssign: 'LEAD_UNASSIGN_CREATE',
  leadSearch: 'LEAD_SEARCH_READ',
  leadImport: 'LEAD_IMPORT',
  LeadCreateUserDefinedBusiness: 'BUSINESS_LEAD_CREATE',
  downloadPhoneCallExcel: 'LEAD_EXPORT_DYNAMIC_READ',
  downloadPhoneCallExcelPerson: 'LEAD_EXPORT_DYNAMIC_READ',
  leadCreate: 'LEAD_ACTION_CREATE',
  LeadCreateUserDefined: 'LEAD_CREATE',

  unTagging: 'TAG_UNTAG_CREATE',
  tagging: 'TAG_TAGGING_CREATE',
  tagManagement: 'TAG_MANAGEMENT',
  tagDelete: 'TAG_DELETE',
  tagUpdate: 'TAG_UPDATE',
  personalLeadTagsTab: 'TAG_LOAD_BY_TAG_ID_READ',

  templateManualLoad: 'TEMPLATE_SEARCH_CREATE',
  templateManualUpdate: 'TEMPLATE_UPDATE',
  templateManualCreate: 'TEMPLATE_CREATE',
  templateManaulActionCreate: 'TEMPLATE_ACTION_CREATE',

  templateSystemicLoad: 'SYSTEMIC_TEMPLATE_SEARCH_CREATE',
  templateSystemicUpdate: 'SYSTEMIC_TEMPLATE_UPDATE',
  templateSystemicView: 'SYSTEMIC_TEMPLATE_READ',
  templateSystemicAction: 'SYSTEMIC_TEMPLATE_ACTION_CREATE',
  templateSystemicDelete: 'SYSTEMIC_TEMPLATE_DELETE',
  templateSystemicCreate: 'SYSTEMIC_TEMPLATE_CREATE',

  productSettingsLoad: 'ACTION_NOTIFICATION',
  productSettingsCreate: 'ACTION_NOTIFICATION_CREATE',
  productSettingsDelete: 'ACTION_NOTIFICATION_DELETE',
  productSettingsUpdate: 'ACTION_NOTIFICATION_PRODUCT_UPDATE',
  productSettingActivate: 'ACTION_NOTIFICATION_ACTIVATE',

  opprotunityDelete: 'OPPORTUNITY_DELETE',

  voipCallCreate: 'VOIP_CALL_CREATE',
  voipCallAllCreate: 'VOIP_CALL_ALL_CREATE',
  voipCallClickToCall: 'VOIP_CALL_CLICK_TO_ALL_CREATE',

  aclGroupCreate: 'ACL_GROUP_CREATE',
  aclGroupLoad: 'ACL_GROUP_READ',
  aclGroupUpdate: 'ACL_GROUP_UPDATE',
  aclGroupDelete: 'ACL_GROUP_DELETE',

  saleProductCreate: 'SALE_PRODUCT_CREATE',
  saleProductLoad: 'SALE_PRODUCT_READ',
  saleProudctUpdate: 'SALE_PRODUCT_UPDATE',
  saleProudctReadAll: 'SALE_PRODUCT_ALL',
  saleOpprotunitesCreate: 'SALE_OPPORTUNITY_CREATE',
  saleOpprotunitesUpdate: 'SALE_OPPORTUNITY_UPDATE',

  sessionCreate: 'SESSION_CREATE',
  sessionLoad: 'SESSION_READ',
  formManagement: 'FORM_MANAGEMENT',
  templateManagement: 'TEMPLATE_MANAGEMENT',
  kycTimeManagement: 'HUMAN_RESOURCE_GET_INIT_MEETINGS_READ',

  organizationSectionAllRead: 'ORGANIZATION_SECTION_ALL_READ',
  organizationSectionUpdate: 'ORGANIZATION_SECTION_UPDATE',
  organizationSectionDelete: 'ORGANIZATION_SECTION_DELETE',
  organizanizationSectionCreate: 'ORGANIZATION_SECTION_CREATE',

  toolsSitadInquiryRead: 'TOOLS_SITAAD_INQUIRY_READ',
  toolsSitaadInfoAndImageRead: 'TOOLS_SITAAD_INFO_AND_IMAGE_READ',
  toolsSejamInquiryRead: 'TOOLS_SJM_INQUIRY_READ',
  toolsAccountInquiryIban: 'ACCOUNT_INQUIRY_IBAN_READ',
  toolsPostAddressStringRead: 'POST_ADDRESS_STRING_READ',
  toolsShahcarPhoneOwnership: 'TOOLS_SHAHKAR_PHONE_OWNERSHIP_READ',
  toolsCardNumberToIban: 'FARABOOM_IBAN_BY_CARD_READ',
  toolsChangeNeshanUserStatus: 'NESHAN_USER_INQUIRY_READ',
  toolsBankCreditCardOcr: 'CREDIT_CARD_OCR_READ',
  roleChequeQrRead: 'CHEQUE_QR_READ',
  toolsNationalCardOcr: 'NATIONAL_CARD_OCR_READ',
  toolsPersonScoreCredit: 'PERSON_CREDIT_SCORING_CREATE',
  toolsLegalScoreCredit: 'LEGAL_CREDIT_SCORING_CREATE',
  toolsSejamRefetchUpdate: 'SEJAM_REFETCH_UPDATE',

  columnNewLeadField: 'COLUMN_LEAD_FIELD_CREATE',
  columnUpdateLeadFields: 'COLUMN_UPDATE_ORDER_UPDATE',
  columnUpdateLeadField: 'COLUMN_UPDATE_LEAD_FIELD',
  columnDeleteLedField: 'COLUMN_LEAD_FIELD_DELETE',

  kycApproveCreate: 'KYC_APPROVE_CREATE',
  kycRejectCreate: 'KYC_REJECT_CREATE',

  opportunityAction: 'OPPORTUNITY_FULL_READ',
  opprotunityAllProducts: 'OPPORTUNITY_ALL_PRODUCTS',

  branchFindByCode: 'BRANCH_FIND_BY_CODE_READ',
  branchCreate: 'BRANCH_REGISTER_CREATE',
  branchDelete: 'BRANCH_DELETE',
  branchAllRead: 'BRANCH_FIND_READ',
  branchChangeStatus: 'BRANCH_CHANGE_STATUS_CREATE',

  representativeFindByCode: 'REPRESENTATIVE_FIND_BY_CODE_READ',
  representativeCreate: 'REPRESENTATIVE_REGISTER_CREATE',
  representativeDelete: 'REPRESENTATIVE_DELETE',
  representativeChangeStatus: 'REPRESENTATIVE_CHANGE_STATUS_CREATE',

  employeRegister: 'EMPLOYEE_REGISTER_CREATE',
  employeeAllRead: 'EMPLOYEE_ALL_READ',
  employeeActivate: 'ROLE_UNIT_EMPLOYEE_ACTIVATE_CREATE',

  portfolioProfileRead: 'PROFILE_PORTFOLIO_READ',
  sejamVideoKycAllRead: 'KYC_VIDEO_SEARCH_READ',
  kianVideoKycAllRead: 'KYC_KIAN_SEARCH_READ',

  deleteOperationBranchRelation: 'OPERATIONAL_BRANCH_RELATION_DELETE',
  getDataOperationBranchRelation: 'OPERATIONAL_BRANCH_RELATION_GRID_READ',
  createOperationBranchRelation: 'OPERATIONAL_BRANCH_RELATION_CREATE',
  operationBranchRelation: 'OPERATIONAL_BRANCH_RELATION',

  employeeEditRoleAction: 'ACL_UNIT_EMP_GROUP_ASSIGN_CREATE',
  dashboardCardsRead: 'DASHBOARD_CARDS_READ',
  generalReportRead: 'QUERY_GENERATOR_CREATE',

  legalLeadSendSms: 'BUSINESS_LEAD_SEND_SMS_UPDATE',
  legalLeadSendEmail: 'BUSINESS_LEAD_SEND_EMAIL_UPDATE',
  legalLeadAssign: 'BUSINESS_LEAD_ASSIGN_UPDATE',
  legalLeadUnAssign: 'BUSINESS_LEAD_UNASSIGN_UPDATE',
  legalLeadTag: 'BUSINESS_LEAD_TAG_UPDATE',
  legalLeadUnTag: 'BUSINESS_LEAD_UNTAG_UPDATE',
  legalLeadChangeStatus: 'BUSINESS_LEAD_CHANGE_STATUS_UPDATE',

  individualLeadSendSms: 'PERSON_LEAD_SEND_SMS_UPDATE',
  individualLeadSendEmail: 'PERSON_LEAD_SEND_EMAIL_UPDATE',
  individualLeadAssign: 'PERSON_LEAD_ASSIGN_UPDATE',
  individualLeadUnAssign: 'PERSON_LEAD_UNASSIGN_UPDATE',
  individualLeadTag: 'PERSON_LEAD_TAG_UPDATE',
  individualLeadUnTag: 'PERSON_LEAD_UNTAG_UPDATE',
  individualLeadChangeStatus: 'PERSON_LEAD_CHANGE_STATUS_UPDATE',
  personLeadUpdate: 'PERSON_LEAD_READ',
  businessLeadUpdate: 'BUSINESS_LEAD_UPDATE',
  leadRelationCreate: 'LEAD_RELATION_CREATE',
  leadRelationDelete: 'LEAD_RELATION_DELETE',
  leadRelationRead: 'LEAD_RELATION_READ',
  leadUpdate: 'LEAD_UPDATE',

  dispatchGroupsTable: 'DISPATCH_GROUP_GRID_READ',
  dispatchGroupsCreate: 'DISPATCH_GROUP_CREATE',
  dispatchGroupsEdit: 'DISPATCH_GROUP_UPDATE',
  dispatchGroupsDelete: 'DISPATCH_GROUP_DELETE',
  dispatchGroupsShow: 'DISPATCH_GROUP_READ',

  kycLevelReadAll: 'KYC_LEVEL_MANAGEMENT',
  kycLevelRead: 'KYC_LEVEL_MANAGEMENT_READ',
  kycLevelCreate: 'KYC_LEVEL_MANAGEMENT_CREATE',
  kycLevelUpdate: 'KYC_LEVEL_MANAGEMENT_UPDATE',
  kycLevelDelete: 'KYC_LEVEL_MANAGEMENT_DELETE',

  rasmioCompanyInfoInquiry: 'RASMIO_COMPANY_DETAIL_READ',

  agentRegisterCreate: 'AGENT_REGISTER_CREATE',
  agentFindRead: 'AGENT_FIND_READ',
  agentFindByCode: 'AGENT_FIND_BY_CODE_READ',
  agentChangeStatus: 'AGENT_CHANGE_STATUS_CREATE',
  agentDelete: 'AGENT_DELETE',
};

export const isAclSkipped = lists => lists?.includes('ACL_SKIPPED');
