export const docType = {
  BIRTH_CERTIFICATE: 'شناسنامه',
  BIRTH_CERTIFICATE_DESCRIPTION: 'توضیحات شناسنامه',
  NATIONAL_CARD_BACK: 'پشت کارت ملی',
  NATIONAL_CARD_FRONT: 'کارت ملی',
  EDUCATION: 'مدرک تحصیلی',
  KYC_VERIFICATION: 'تایید احراز هویت',
  LOGO: 'لوگوی شرکت',
  OWNERSHIP: 'سند مالکیت',
  LICENSE: 'جواز کسب',
  BUSINESS_LICENSE: 'روزنامه رسمی',
  AGENT_SENTENCE: 'حکم نماینده سازمان',
  SIGNATURE_IMAGE: 'عکس امضا',
  SANA_CONFIRMATION: 'تاییدیه ثنا',
  BANK_DRAFT: 'چک صیادی / سفته',
  LEASE_CONTRACT: 'اجاره نامه / سند ملک',
  WAGE_ASSIGNMENT: 'گواهی کسر از حقوق',
  PAYCHECK_SCAN: 'فیش حقوقی',
  SIGNATURE_VERIFICATION: 'گواهی امضا',
  BANK_ACCOUNT_PRINT: 'پرینت حساب بانکی',
  GUARANTY_LETTER: 'ضمانت نامه',
  CV: 'رزومه',
  BUSINESS_PERMIT: 'جواز کسب و کار',
  SIGN_OFFICERS: 'آگهی آخرین امضا داران مجاز',
  DEPOSITARY_LETTER: 'سپرده نامه',
  FOREMAN_CARD: 'کارت مباشرت',
  STATUTE: 'اساسنامه',
  ESTABLISHMENT_ANNOUNCEMENT: 'آگهی تاسیس',
  OFFICIAL_NEWSPAPER: 'روزنامه رسمی',
  OTHER: 'سایر',
};
