export const rejectionReasonTranslate = {
  rejectDesc: '',
  appUpdate: '',
  certificateDescriptionStatus: 'تصویر توضیحات شناسنامه',
  nationalCardFrontStatus: 'تصویر جلو کارت ملی',
  nationalCardBackStatus: 'تصویر پشت کارت ملی',
  certificateStatus: 'تصاویر شناسنامه',
  educationCertificateStatus: 'تصویر مدرک تحصیلی',
  logoStatus: 'لوگو شرکت',
  licenseStatus: 'جواز کسب',
  ownershipStatus: 'وضعیت مالکیت',
  documentsStatus: 'اسناد',
  businessDocumentsStatus: 'اسناد کسب‌ و کار',
  personalInfoStatus: 'مشخصات فردی',
  businessInfoStatus: 'مشخصات کسب و کار',
  contactStatus: 'مشخصات تماس',
  businessContactStatus: 'مشخصات تماس کسب و کار',
  shebaNoStatus: 'شماره شبا',
  brokerageAccountStatus: 'حساب کارگزاری',
  emailStatus: 'ایمیل',
  sejamStatus: 'سجام',
  editDocuments: '',
  editBusinessDocuments: '',
  editPersonalInfo: '',
  editBusinessInfo: '',
  editContact: '',
  editBusinessContact: '',
  editShebaNo: '',
  editBrokerageAccount: '',
  editEmail: '',
  editSejam: '',
  editable: '',
  bourseCodesStatus: 'کد بورسی',
  financialKnowledgeStatus: 'دانش مالی',
  workInfoStatus: 'اطلاعات شغلی ',
  bankAccountsStatus: 'حساب بانکی',
  fetchSejamDataStatus: 'حساب سجام',
  sejamOTPStatus: 'otp سجام',
  agentSentenceStatus: 'حکم نماینده',
  officialNewspaperStatus: 'روزنامه رسمی',
  statuteStatus: 'اساسنامه',
  establishmentAnnouncementStatus: 'آگهی تاسیس',
  creditScoreStatus: 'اعتبارسنجی حقوقی',
  personScoreStatus: ' اعتبارسنجی حقیقی',
  financialInfoStatus: ' اطلاعات مالی',
  stakeHoldersStatus: 'ذینفعان',
  facilityDetailStatus: ' جزئیات تسهیلات',
  guarantorsStatus: 'ضامنین',
  signatureImageStaus: 'عکس امضا',
  signatureVerificationStatus: 'گواهی امضا',
  sanaConfirmationStatus: 'تاییدیه ثنا',
  paycheckScanStatus: 'فیش حقوقی',
  bankDraftStatus: 'چک صیادی/سفته',
  leaseContractStatus: 'تصویر اجاره نامه / سند',
  bankAccountPrintStatus: 'پرینت حساب بانکی سه ماهه',
  wageAssignmentStatus: 'گواهی کسر از حقوق',
  kycSelfieImageStatus: 'تصویر سلفی کاربر',
  kycVideoCaptchaStatus: 'ویدئو کاربر',
};
